Pegasus/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Pegasus.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string User { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string Password { get; set; }

        [Display(Name = "Lembrar da Senha?")]
        public bool RememberMe { get; set; }
    }

    public class ForgotViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required]
        public string Url { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]

        [Display(Name = "Nome Completo")]
        public string Nome { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "O/A {0} deve ter no mínimo {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirmar Senha")]
        [Compare("Password", ErrorMessage = "A senha e a senha de confirmação não correspondem.")]
        public string ConfirmPassword { get; set; }

        [Required]
        public string Url { get; set; }
    }

    public class ResetPasswordViewModel
    {
        //[Required]
        //[EmailAddress]
        //[Display(Name = "Email")]
        //public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "O/A {0} deve ter no mínimo {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar senha")]
        [Compare("Password", ErrorMessage = "A senha e a senha de confirmação não coincidem.")]
        public string ConfirmPassword { get; set; }

        public Guid Code { get; set; }

        [Required]
        public string Url { get; set; }
    }


}

Pegasus/Areas/Admin/Controllers/PermissionController.cs
using BusinessLayer.Commom;
using BusinessLayer.Helpers;
using BusinessLayer.Security;
using DataLayer.DbSystem.Context;
using Pegasus.Areas.Admin.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Pegasus.Areas.Admin.Controllers
{
    [SystemAuthorize(Roles = "ADMIN")]
    public class PermissionController : BaseController
    {
        DbSystemContext _context = new DbSystemContext();

        public PermissionController()
        {
            _context = new DbSystemContext();
        }

        // GET: Admin/Permission
        public ActionResult Index(string searchString = "")
        {
            var vm = new PermissionsByUserViewModel
            {
                AvaliablePermissions = SelectListItemHelper.GetAllAvailablePermissionsToUser(searchString),
                AppliedPermissions = SelectListItemHelper.GetAllUserPermissions(searchString),
                currentSearch = searchString,
                userExist = _context.EfSystemUser.Where(P => P.Email == searchString).Any()
            };
            return Request.IsAjaxRequest() ? (ActionResult)PartialView("_List", vm) : View(vm);
        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            string[] itemsAvaliable = form.AllKeys.Contains("SelectedAvaliable") ? form["SelectedAvaliable"].Split(new char[] { ',' }) : new string[0];
            string[] itemsApplied = form.AllKeys.Contains("SelectedApplied") ? form["SelectedApplied"].Split(new char[] { ',' }) : new string[0];
            string userName = form.AllKeys.Contains("currentSearch") ? form["currentSearch"] : null;

            if (userName != null)
            {
                try
                {
                    bool _result = false;
                    var _user = _context.EfSystemUser.Where(P => P.Email == userName).FirstOrDefault();
                    foreach (var item in itemsAvaliable)
                    {
                        var _permissions = _context.EfSystemPermissions.Where(p => p.PermissionId.ToString().Equals(item)).FirstOrDefault();
                        _user.PermissionsCollection.Remove(_permissions);
                        _context.SaveChanges();
                        _result = true;
                    }
                    foreach (var item in itemsApplied)
                    {
                        var _permissions = _context.EfSystemPermissions.Where(p => p.PermissionId.ToString().Equals(item)).Where(p => !p.SystemUserCollection
                                .Where(P => P.Email == userName).Any()).FirstOrDefault();
                        if (_permissions != null)
                        {
                            _user.PermissionsCollection.Add(_permissions);
                            _context.SaveChanges();
                        }
                        _result = true;
                    }
                    if (_result)
                    {
                        ShowSuccessMessage("Successfully applied permissions.");
                    }
                }
                catch (Exception ex)
                {
                    ShowDangerMessage(ex.Message);
                }
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Pegasus/Areas/Support/Controllers/PermissionsController.cs
using BusinessLayer.Commom;
using BusinessLayer.Security;
using DataLayer.DbSystem.Context;
using DataLayer.DbSystem.Models;
using System;
using System.Net;
using System.Web.Mvc;

namespace Pegasus.Areas.Support.Controllers
{
    [SystemAuthorize(Roles = "SUPORTE")]
    public class PermissionsController : BaseController
    {
        DbSystemContext _context = new DbSystemContext();

        public PermissionsController()
        {
            _context = new DbSystemContext();
        }

        public ActionResult Index()
        {
            return View(_context.EfSystemPermissions);
        }

        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tbPermissions = _context.EfSystemPermissions.Find(id);
            if (tbPermissions == null)
            {
                return HttpNotFound();
            }
            return View(tbPermissions);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PermissionId,Name,Description,Active")] TbSystemPermissions tbPermissions)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    tbPermissions.PermissionId = Guid.NewGuid();
                    tbPermissions.Name = tbPermissions.Name.TrimToUpper();
                    tbPermissions.Description = tbPermissions.Description.TrimToUpper();
                    _context.EfSystemPermissions.Add(tbPermissions);
                    _context.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                ShowDangerMessage(ex.InnerException.InnerException.Message);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tbPermissions = _context.EfSystemPermissions.Find(id);
            if (tbPermissions == null)
            {
                return HttpNotFound();
            }
            return View(tbPermissions);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PermissionId,Name,Description,Active")] TbSystemPermissions tbPermissions)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.EfSystemPermissions.Add(tbPermissions);
                    _context.Entry(tbPermissions).State = System.Data.Entity.EntityState.Modified;
                    _context.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                ShowDangerMessage(ex.InnerException.InnerException.Message);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tbPermissions = _context.EfSystemPermissions.Find(id);
            if (tbPermissions == null)
            {
                return HttpNotFound();
            }
            return View(tbPermissions);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            try
            {
                var tbPermissions = _context.EfSystemPermissions.Find(id);
                tbPermissions.Active = false;
                _context.EfSystemPermissions.Add(tbPermissions);
                _context.Entry(tbPermissions).State = System.Data.Entity.EntityState.Modified;
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                ShowDangerMessage(ex.InnerException.InnerException.Message);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Pegasus/Controllers/ProfileController.cs
using BusinessLayer.Commom;
using BusinessLayer.Models;
using BusinessLayer.Security;
using DataLayer.DbSystem.Context;
using DataLayer.DbSystem.Models;
using Pegasus.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pegasus.Controllers
{
    [Authorize]
    public class ProfileController : BaseController
    {
       
        DbSystemContext _context = new DbSystemContext();
        public ActionResult Index()
        {
            var user = _context.EfSystemUser.Where(P => P.User == User.Identity.Name).FirstOrDefault();
            UsersAlls Userclass = new UsersAlls();
            Userclass.CEP = user.CEP;
            Userclass.Email = user.Email;
            Userclass.Endereço = user.Endereço;
            Userclass.Name = user.Name;
            Userclass.Senha = user.Senha;
            Userclass.Telefone = user.Telefone;
            Userclass.User = user.User;
   
            return View(Userclass);
        }

        [HttpPost]
        public ActionResult Index(UsersAlls users)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = _context.EfSystemUser.Where(P => P.User == User.Identity.Name).FirstOrDefault();
                    TbSystemUser Userclass = new TbSystemUser();
                    Userclass.Active = user.Active;
                    Userclass.LastAccess = user.LastAccess;
                    Userclass.UserId = user.UserId;
                    Userclass.CEP = users.CEP;
                    Userclass.Cpf = user.Cpf;
                    Userclass.Email = users.Email;
                    Userclass.Endereço = users.Endereço;
                    Userclass.Name = users.Name;
                    Userclass.Senha = users.Senha;
                    Userclass.Telefone = users.Telefone;
                    Userclass.User = users.User;

                    _context.Entry(User).State = EntityState.Modified;
                    _context.SaveChanges();
                }
                else
                {
                    ShowDangerMessage(ModelState);
                }
            }
            catch (Exception ex)
            {
                ShowDangerMessage(ex.InnerException.Message);
            }
              return View();

          
        }

    }
}

Pegasus/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 0.0.1
    </div>
    <strong>Copyright &copy; 2019 <a href="#">Danilo Rosa</a>.</strong> All rights
    reserved.
</footer>

Pegasus/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Pegasus/Views/Shared/_Layout - Cópia .cshtml
<!doctype html>
<html lang="en">
 
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MSV</title>

    <!-- Bootstrap CSS -->
    @Styles.Render("~/Content/css")

    @Styles.Render("~/Content/datatables")
    @Styles.Render("~/Content/fonts")

    @Scripts.Render("~/bundles/scripts")
    @Scripts.Render("~/bundles/datatable")
</head>

<body>
    <!-- ============================================================== -->
    <!-- main wrapper -->
    <!-- ============================================================== -->
    <div class="dashboard-main-wrapper">
        <!-- ============================================================== -->
        <!-- navbar -->
        <!-- ============================================================== -->
        @Html.Partial("_MenuHeadBar")
        <!-- ============================================================== -->
        <!-- end navbar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- left sidebar -->
        <!-- ============================================================== -->
        @Html.Partial("_MenuLeftBar")
        <!-- ============================================================== -->
        <!-- end left sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- wrapper  -->
        <!-- ============================================================== -->
        <div class="dashboard-wrapper">
            <div class="main-container">
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">

                        @RenderBody()

                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            @Html.Partial("_Footer")
            <!-- ============================================================== -->
            <!-- end footer -->
            <!-- ============================================================== -->
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- end main wrapper -->
    <!-- ============================================================== -->
    <!-- Optional JavaScript -->


    <div class="modal fade" tabindex="-1" role="dialog" id="modal" aria-hidden="true">


    </div>

</body>
 
</html>

Pegasus/Views/Shared/_Layout.cshtml
@{ 
    var current_Oficina = Session[SystemConstants.SessionOficina] as DataLayer.DbSystem.Models.TbOperationCadastroOficina;
}
@using BusinessLayer.Security;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SMV Sistema de Manutenção Veicular </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @Styles.Render("~/Content/css")

    @Styles.Render("~/Content/datatables")
    @Styles.Render("~/Content/fonts")

    @Scripts.Render("~/bundles/scripts")
    @Scripts.Render("~/bundles/datatable")

    @Styles.Render("~/Content/load")

    @Scripts.Render("~/bundles/load")
</head>
<body class="hold-transition sidebar-mini layout-footer-fixed">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>

            </ul>


            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Brand Logo -->
       
                    <img src="~/Images/SMV.jpeg"
                         alt="SMV"
                         class="brand-image "
                         style="opacity: .8" />
                    <span class="brand-text font-weight-light"></span>
              
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-secondary elevation-4">
            <!-- Brand Logo -->
            @if (current_Oficina != null) {
                <a href="/" class="brand-link">
                    <img src="@current_Oficina.LogoBase64"
                         
                         class="brand-image "
                         style="opacity: 1; width:10%; height:10%" />
                    <span class="brand-text font-weight-light">@current_Oficina.Name</span>
                </a>
            }
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                  
                    <div class="info">
                        <a href="#" class="d-block"><span><i class="fa fa-fw fa-user"></i></span> @Session["displayname"]</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                @Html.Partial("_MenuHeadBar")
                <!-- /.sidebar-menu -->
            </div>
      
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <!-- Main content -->
                    <section class="content">
                         <section id="DivAlertMessage" class="content-header">
                            @if (@TempData["message"] != null)
                            {
                     
                                <div class="alert @TempData["messageType"] alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <strong>@TempData["message"]</strong>
                                </div>
                            }
                        </section>
                        @RenderBody()
                        @*<!-- Default box -->
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">Title</h3>

                                    <div class="card-tools">
                                        <button type="button" class="btn btn-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                                            <i class="fas fa-minus"></i>
                                        </button>
                                        <button type="button" class="btn btn-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                                            <i class="fas fa-times"></i>
                                        </button>
                                    </div>
                                </div>
                                <div class="card-body">
                                    Start creating your amazing application!
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    Footer
                                </div>
                                <!-- /.card-footer-->
                            </div>*@
                        <!-- /.card -->

                    </section>
                    <!-- /.content -->
                </div>
            </div>
        </div>
        <!-- /.content-wrapper -->
        @Html.Partial("_Footer")



    </div>
    <div class="modal fade" tabindex="-1" role="dialog" id="modal" aria-hidden="true"></div>
</body>
</html>

Pegasus/Views/Shared/_MenuHeadBar.cshtml
@using BusinessLayer.Security
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
        @if (SystemSecurityRoles.IsInRole("ADMIN"))
    {
        <li class="nav-header">Administração</li>


        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Permission", new { Area = "Admin" })">
                <i class="fa fa-fw fa-ban"></i>
                <p>
                    Conceder Acesso
                    <span class="badge badge-info right"></span>
                </p>
            </a>
        </li>

}

        @if (SystemSecurityRoles.IsInRole("SUPORTE"))
    {
        <li class="nav-header">Suporte</li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "CadastroOficina", new { Area = "Support" })">
                <i class="fa fa-fw fa-industry"></i>
                <p>
                    Cadastrar Oficinas
                    <span class="badge badge-info right"></span>
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Permissions", new { Area = "Support" })">
                <i class="fa fa-fw fa-minus-circle">
                </i>
                <p>
                    Permissoes
                    <span class="badge badge-info right"></span>
                </p>


            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "CadastroServicoes", new { Area = "Support" })">
                <i class="fa fa-fw fa-server">
                </i>
                <p>
                    Cadastrar Servicos
                    <span class="badge badge-info right"></span>
                </p>
            </a>
        </li>

}

        @if (SystemSecurityRoles.IsInRole("ADMIN"))
    {
        <li class="nav-header">Oficina</li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "CadastroCliente", new { Area = "Oficina" })">
                <i class="fa fa-fw fa-address-book">
                </i>
                <p>
                    Clientes
                    <span class="badge badge-info right"></span>
                </p>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "OrdemDeServicoes", new { Area = "Oficina" })">
                <i class="fa fa-fw fa-tasks"></i>
                <p>Todos os Pedidos</p>
                <span class="badge badge-info right"></span>
            </a>
        </li>
        @*<li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "CadastroVeiculo", new { Area = "Oficina" })">
                <i class="fa fa-fw fa-car"></i>
                <p>Cadastrar Veiculo</p>

                <span class="badge badge-info right"></span>
            </a>
        </li>*@
        <li class="nav-item">

            <a class="nav-link" href="@Url.Action("Index", "Home", new { Area = "" })">
                <i class="fa fa-fw fa-industry"></i>

                <p>Escolher Oficina </p> <span class="badge badge-info right"></span>
            </a>

        </li>
}

        <li class="nav-header">Usuario</li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Profile", new { Area = "" })">
                <i class="fa fa-fw fa-user"></i>
                <p>Perfil</p>
                <span class="badge badge-info right"></span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "OrdemDeServicoes", new { Area = "Oficina" })">
                <i class="fa fa-fw fa-tasks"></i>
                <p>Historico de Servicos</p>
                <span class="badge badge-info right"></span>
            </a>
        </li>

        <li class="nav-item">

            <a class="nav-link" href="@Url.Action("Logout", "Account", new { Area = "" })">
                <i class="fas fa-sign-out-alt"></i>

                <p>Sair </p> <span class="badge badge-info right"></span>
            </a>

        </li>

    </ul>
</nav>

Pegasus/Views/Shared/_MenuLeftBar.cshtml
<div class="nav-left-sidebar sidebar-dark">
    <div class="menu-list">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="d-xl-none d-lg-none" href="#">Menu</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav flex-column">

                    <li class="nav-divider">
                        Oficina
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","CadastroCliente", new { Area = "Oficina" })"><i class="fa fa-fw fa-user-circle"></i>Clientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","CadastroServicoes", new { Area = "Oficina" })"><i class="fa fa-fw fa-user-circle"></i>Servicos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","CadastroTipoDeServicos", new { Area = "Oficina" })"><i class="fa fa-fw fa-user-circle"></i>Tipo do Servicos</a>
                    </li>


                    <li class="nav-divider">
                        Administração
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","CadastroOficina", new { Area = "Oficina" })"><i class="fa fa-fw fa-ban"></i>Oficinas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Permission", new { Area = "Admin" })"><i class="fa fa-fw fa-ban"></i>Permissoes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Employees", new { Area = "Admin" })"><i class="fa fa-fw fa-user-circle"></i>Usuarios</a>
                    </li>


                    <li class="nav-divider">
                        Manutenções
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","OrdemDeServicoes", new { Area = "Oficina" })"><i class="fa fa-fw fa-user-circle"></i>Lista de Solicitações Pendentes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","CadastroVeiculo", new { Area = "Oficina" })"><i class="fa fa-fw fa-user-circle"></i>Solicitar Manutenção</a>
                    </li>


                    <li class="nav-divider">
                        Suporte
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Permissions", new { Area = "Support" })"><i class="fa fa-fw fa-ban"></i>Permissoes</a>
                        @*<a class="nav-link" href="@Url.Action("Index","Companies", new { Area = "Suport" })"><i class="fa fa-fw fa-ban"></i>Permissoes</a>*@

                    </li>


                    <li class="nav-divider">
                        Usuario
                    </li>
                    <li class="nav-item">

                        <a class="nav-link" href="@Url.Action("Logout","Account", new { Area = "" })"><i class="fa fa-fw fa-ban"></i>Sair</a>

                    </li>

                </ul>
            </div>
        </nav>
    </div>
</div>