Pegasus/Areas/Oficina/Controllers/CadastroOficinaController.cs
using BusinessLayer.Commom;
using BusinessLayer.Helpers;
using BusinessLayer.Models;
using BusinessLayer.Security;
using DataLayer.DbSystem.Context;
using DataLayer.DbSystem.Models;
using Pegasus.Areas.Oficina.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Pegasus.Areas.Oficina.Controllers
{
    [SystemAuthorize(Roles = "OFICINA")]
    public class CadastroOficinaController : BaseController
    {
        DbSystemContext _context = new DbSystemContext();

        public CadastroOficinaController()
        {

        }
        public ActionResult Index()
        {
            return View(_context.EfCadastroOficina.ToList());
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OficinaModelView oficinaModelView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TbOperationCadastroOficina tbOperationCadastroOficina = new TbOperationCadastroOficina();
                    tbOperationCadastroOficina.OperationCadastroOficinaId = Guid.NewGuid();

                    var teste = SaveFileHelper.ConvertByArray(oficinaModelView.Files.InputStream);
                    tbOperationCadastroOficina.Name = oficinaModelView.Name;
                    tbOperationCadastroOficina.LogoBase64 = "data:image/jpeg;base64,"+ Convert.ToBase64String(teste);
                    tbOperationCadastroOficina.Active = oficinaModelView.Active;
                    tbOperationCadastroOficina.ContentType = oficinaModelView.Files.ContentType;
                    tbOperationCadastroOficina.Created = DateTime.Now;
                    tbOperationCadastroOficina.Modified = DateTime.Now;
                    tbOperationCadastroOficina.UserId = _context.EfSystemUser.Where(P => P.User == User.Identity.Name).FirstOrDefault().UserId;
                    _context.EfCadastroOficina.Add(tbOperationCadastroOficina);
                    _context.SaveChanges();
                }
                else
                {
                    ShowDangerMessage(ModelState);
                }
            }
            catch (Exception ex)
            {
                ShowDangerMessage(ex);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tbCadastroOficina = _context.EfCadastroOficina.Find(id);
            if (tbCadastroOficina == null)
            {
                return HttpNotFound();
            }
            OficinaModelView oficinaModelView = new OficinaModelView();
            oficinaModelView.Name = tbCadastroOficina.Name;
            oficinaModelView.OperationCadastroOficinaId = tbCadastroOficina.OperationCadastroOficinaId;
            oficinaModelView.Base64 = tbCadastroOficina.LogoBase64;
            oficinaModelView.Active = tbCadastroOficina.Active;



            oficinaModelView.Files = (HttpPostedFileBase)new MemoryPostedFile(Convert.FromBase64String(oficinaModelView.Base64.Replace("data:image/jpeg;base64,","")), "Logo"); 
            return View(oficinaModelView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OficinaModelView oficinaModelView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TbOperationCadastroOficina tbOperationCadastroOficina = new TbOperationCadastroOficina();
                    var tbCadastroOficina = _context.EfCadastroOficina.Find(oficinaModelView.OperationCadastroOficinaId);
                    tbOperationCadastroOficina.OperationCadastroOficinaId = oficinaModelView.OperationCadastroOficinaId;

                    var teste = SaveFileHelper.ConvertByArray(oficinaModelView.Files.InputStream);
                    tbCadastroOficina.Name = oficinaModelView.Name;
                    tbCadastroOficina.LogoBase64 = "data:image/jpeg;base64," + Convert.ToBase64String(teste);
                    tbCadastroOficina.Active = oficinaModelView.Active;
                    tbCadastroOficina.ContentType = oficinaModelView.Files.ContentType;
                    //tbOperationCadastroOficina.Created = tbCadastroOficina.Created;
                    tbCadastroOficina.Modified = DateTime.Now;
               

                    _context.Entry(tbCadastroOficina).State = EntityState.Modified;
                    _context.SaveChanges();
                }
                else
                {
                    ShowDangerMessage(ModelState);
                }
            }
            catch (Exception ex)
            {
                ShowDangerMessage(ex);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tbCompanies = _context.EfCadastroOficina.Find(id);
            if (tbCompanies == null)
            {
                return HttpNotFound();
            }
            return View(tbCompanies);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            try
            {
                var tbOperationCadastroOficina = _context.EfCadastroOficina.Find(id);
                tbOperationCadastroOficina.Active = false;
                _context.EfCadastroOficina.Add(tbOperationCadastroOficina);
                _context.Entry(tbOperationCadastroOficina).State = EntityState.Modified;
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                ShowDangerMessage(ex.InnerException.Message);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Pegasus/Areas/Support/Controllers/CadastroOficinaController.cs
using BusinessLayer.Commom;
using BusinessLayer.Helpers;
using BusinessLayer.Models;
using BusinessLayer.Security;
using DataLayer.DbSystem.Context;
using DataLayer.DbSystem.Models;
using Pegasus.Areas.Oficina.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Pegasus.Areas.Support.Controllers
{
    [SystemAuthorize(Roles = "SUPORTE")]
    public class CadastroOficinaController : BaseController
    {
        DbSystemContext _context = new DbSystemContext();

        public CadastroOficinaController()
        {

        }
        public ActionResult Index()
        {
            return View(_context.EfCadastroOficina.ToList());
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OficinaModelView oficinaModelView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TbOperationCadastroOficina tbOperationCadastroOficina = new TbOperationCadastroOficina();
                    tbOperationCadastroOficina.OperationCadastroOficinaId = Guid.NewGuid();

                    var teste = SaveFileHelper.ConvertByArray(oficinaModelView.Files.InputStream);
                    tbOperationCadastroOficina.Name = oficinaModelView.Name;
                    tbOperationCadastroOficina.LogoBase64 = "data:image/jpeg;base64,"+ Convert.ToBase64String(teste);
                    tbOperationCadastroOficina.Active = oficinaModelView.Active;
                    tbOperationCadastroOficina.ContentType = oficinaModelView.Files.ContentType;
                    tbOperationCadastroOficina.Created = DateTime.Now;
                    tbOperationCadastroOficina.Modified = DateTime.Now;
                    tbOperationCadastroOficina.UserId = _context.EfSystemUser.Where(P => P.User == User.Identity.Name).FirstOrDefault().UserId;
                    _context.EfCadastroOficina.Add(tbOperationCadastroOficina);
                    _context.SaveChanges();
                }
                else
                {
                    ShowDangerMessage(ModelState);
                }
            }
            catch (Exception ex)
            {
                ShowDangerMessage(ex);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tbCadastroOficina = _context.EfCadastroOficina.Find(id);
            if (tbCadastroOficina == null)
            {
                return HttpNotFound();
            }
            OficinaModelView oficinaModelView = new OficinaModelView();
            oficinaModelView.Name = tbCadastroOficina.Name;
            oficinaModelView.OperationCadastroOficinaId = tbCadastroOficina.OperationCadastroOficinaId;
            oficinaModelView.Base64 = tbCadastroOficina.LogoBase64;
            oficinaModelView.Active = tbCadastroOficina.Active;



            oficinaModelView.Files = (HttpPostedFileBase)new MemoryPostedFile(Convert.FromBase64String(oficinaModelView.Base64.Replace("data:image/jpeg;base64,","")), "Logo"); 
            return View(oficinaModelView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OficinaModelView oficinaModelView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TbOperationCadastroOficina tbOperationCadastroOficina = new TbOperationCadastroOficina();
                    var tbCadastroOficina = _context.EfCadastroOficina.Find(oficinaModelView.OperationCadastroOficinaId);
                    tbOperationCadastroOficina.OperationCadastroOficinaId = oficinaModelView.OperationCadastroOficinaId;

                    var teste = SaveFileHelper.ConvertByArray(oficinaModelView.Files.InputStream);
                    tbCadastroOficina.Name = oficinaModelView.Name;
                    tbCadastroOficina.LogoBase64 = "data:image/jpeg;base64," + Convert.ToBase64String(teste);
                    tbCadastroOficina.Active = oficinaModelView.Active;
                    tbCadastroOficina.ContentType = oficinaModelView.Files.ContentType;
                    //tbOperationCadastroOficina.Created = tbCadastroOficina.Created;
                    tbCadastroOficina.Modified = DateTime.Now;
               

                    _context.Entry(tbCadastroOficina).State = EntityState.Modified;
                    _context.SaveChanges();
                }
                else
                {
                    ShowDangerMessage(ModelState);
                }
            }
            catch (Exception ex)
            {
                ShowDangerMessage(ex);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tbCompanies = _context.EfCadastroOficina.Find(id);
            if (tbCompanies == null)
            {
                return HttpNotFound();
            }
            return View(tbCompanies);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            try
            {
                var tbOperationCadastroOficina = _context.EfCadastroOficina.Find(id);
                tbOperationCadastroOficina.Active = false;
                _context.EfCadastroOficina.Add(tbOperationCadastroOficina);
                _context.Entry(tbOperationCadastroOficina).State = EntityState.Modified;
                _context.SaveChanges();
            }
            catch (Exception ex)
            {
                ShowDangerMessage(ex.InnerException.Message);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Pegasus/Areas/Oficina/Views/CadastroOficina/Create.cshtml
@model Pegasus.Areas.Oficina.Models.OficinaModelView


<div class="modal-dialog" role="document">
    <div class="modal-content">
        @using (Html.BeginForm(Html.BeginForm("Create", "CadastroOficina", FormMethod.Post, new { enctype = "multipart/form-data", autocomplete = "off", Area = "Oficina" })))
            {
                @Html.AntiForgeryToken()
   
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Novo</h5>
            <a href="#" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </a>
        </div>
        <div class="modal-body">
            <div class="col-md-12 ">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="form-group">
                        @Html.LabelFor(m => Model.Name, new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        @Html.LabelFor(model => model.Files, htmlAttributes: new { @class = "control-label col-md-2", @for = "input-file-now" })
                        <div class="col-md-12">

                            @Html.TextBoxFor(model => model.Files, new { @class = "dropify", @id = " form-control input-file-now", @type = "file" })

                            @Html.ValidationMessageFor(model => model.Files.FileName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                        <div class="form-group">
                            @Html.LabelFor(m => Model.Active, new { @class = "control-label col-md-2" })
                            <div class="col-md-12">
                                @Html.CheckBoxFor(m => m.Active, new { @class = "checkbox" })
                            </div>
                        </div>



                    </div>
            </div>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn btn-secondary" data-dismiss="modal">Fechar</a>
            <button class="btn btn-primary" type="submit">Salvar</button>
        </div>
        }
    </div>
</div>

<script>

    $(document).ready(function () {
        // Basic
        $('.dropify').dropify();

    });
</script>

Pegasus/Areas/Oficina/Views/CadastroOficina/Delete.cshtml
@model DataLayer.DbSystem.Models.TbOperationCadastroOficina

<div class="modal-dialog">
    <div class="modal-content">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Deletar</h4>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="modal-body">
                <h3>Deseja deletar?</h3>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-danger pull-left" data-dismiss="modal"><span class="fa fa-ban fa-right"></span>Não</button>
                <button type="submit" class="btn btn-success"><span class="fa fa-save fa-right"></span>Sim</button>
            </div>
        }
    </div>
</div>

Pegasus/Areas/Oficina/Views/CadastroOficina/Edit.cshtml
@model Pegasus.Areas.Oficina.Models.OficinaModelView


<div class="modal-dialog" role="document">
    <div class="modal-content">
        @using (Html.BeginForm(Html.BeginForm("Edit", "CadastroOficina", FormMethod.Post, new { enctype = "multipart/form-data", autocomplete = "off", Area = "Oficina" })))
    {
        @Html.AntiForgeryToken()

        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Edit</h5>
            <a href="#" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </a>
        </div>
        <div class="modal-body">
            <div class="col-md-10 col-md-offset-1">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(p=> p.OperationCadastroOficinaId)
                    <div class="form-group">
                        @Html.LabelFor(m => Model.Name, new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">

                        @Html.LabelFor(model => model.Files, htmlAttributes: new { @class = "control-label col-md-2", @for = "input-file-now" })
                        <div class="col-md-12">

                            @Html.TextBoxFor(model => model.Files, new { @class = "dropify", @id = "input-file-now ", @type = "file" })

                            @Html.ValidationMessageFor(model => model.Files.FileName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => Model.Active, new { @class = "control-label col-md-2" })
                        <div class="col-md-12">
                            @Html.CheckBoxFor(m => m.Active, new { @class = "checkbox" })
                        </div>
                    </div>


                </div>
            </div>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn btn-secondary" data-dismiss="modal">Fechar</a>
            <button class="btn btn-primary" type="submit">Salvar</button>
        </div>
}
    </div>
</div>

<script>
    $(document).ready(function () {
     var nameImage = '@MvcHtmlString.Create(Model.Base64)';
        $('.dropify').dropify({
           
        });
    });
    //dropify-wrapper add has-preview

   // dropify-loader change display: none

   // dropify-preview change display: block
</script>

Pegasus/Areas/Oficina/Views/CadastroOficina/Index.cshtml
@model IEnumerable<DataLayer.DbSystem.Models.TbOperationCadastroOficina>
@{
    ViewBag.Title = "Lista de Oficinas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <h1>    @ViewBag.Title</h1>
            </div>
            <div class="col-sm-5">
            </div>
            <div class="col-sm-1">
                <button class="btn btn-block btn-info btn-flat create" data-id="0">
                    <i class="fas fa-plus-circle"></i>
                    Criar
                </button>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>



<div class="container-fluid  dashboard-content">


    <div class="row">
        <!-- ============================================================== -->
        <!-- data table  -->
        <!-- ============================================================== -->
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="mb-0"></h5>
                    <p></p>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="datatable" class="table table-striped table-bordered second" style="width:100%">
                            <thead>
                                <tr>

                                    <th>
                                        Oficina
                                    </th>
                                    <th>
                                        Logo
                                    </th>
                                    <th>
                                        Ativado
                                    </th>
                                    <th>     </th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        <img id="show-code-thumbnail" class="show-code-thumbnail-dark " src="@item.LogoBase64" style="width:80px" />
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Active)
                                    </td>



                                    <td class="text-center btn-group-sm table-menu-buttons">
                                        <button class="btn btn-primary edit" data-toggle="tooltip" data-placement="left" title="Edit" data-id="@item.OperationCadastroOficinaId"><i class="fas fa-pencil-alt"></i></button>
                                        @*<button class="btn btn-default btn-info" data-toggle="tooltip" data-placement="top" title="Details" data-id="@item.UserId"><i class="fas fa-eye"></i></button>*@
                                        <button class="btn btn-danger delete" data-toggle="tooltip" data-placement="right" title="Delete" data-id="@item.OperationCadastroOficinaId"><i class="fas fa-trash-alt"></i></button>
                                    </td>
                                </tr>
                                }

                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- end data table  -->
        <!-- ============================================================== -->
    </div>

</div>